### ISSUE TITLE
ProfileTile Component

### ISSUE THREAD

**Issue by robertlong** [thirdroom/thirdroom#5]
Tasks:
- [ ] Use #2 to show user's avatar preview
- [ ] Display #3 in modal when clicking change avatar button
- [ ] Use #4 to show/edit user name
- [ ] Use #6 to manage state
